# Generated by Django 5.2.17 on 2026-10-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='klíč')),
                ('value', models.CharField(max_length=1000, verbose_name='hodnota')),
            ],
            options={
                'verbose_name': 'nastavení',
                'verbose_name_plural': 'nastavení',
                'ordering': ['key'],
            },
        ),
    ]
