# Generated by Django 5.2.17 on 2026-10-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='jméno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
            ],
            options={
                'verbose_name': 'kadeřnice / kosmetička',
                'verbose_name_plural': 'kadeřnice / kosmetičky',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MakerReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(help_text='Například 1430 pro 14:30.', max_length=4, verbose_name='čas')),
                ('service', models.CharField(max_length=255, verbose_name='služba')),
                ('name', models.CharField(max_length=255, verbose_name='jméno')),
                ('phone', models.CharField(max_length=255, verbose_name='telefon')),
                ('email', models.CharField(max_length=255, verbose_name='e-mail')),
                ('consent', models.BooleanField(verbose_name='souhlas se zpracováním osobních údajů')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='salons.maker', verbose_name='kadeřnice / kosmetička')),
            ],
            options={
                'verbose_name': 'rezervace salonu',
                'verbose_name_plural': 'rezervace salonu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255, verbose_name='služba')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='salons.maker', verbose_name='kadeřnice / kosmetička')),
            ],
            options={
                'verbose_name': 'služba',
                'verbose_name_plural': 'služby',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MakerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(help_text='Například 1430 pro 14:30.', max_length=4, verbose_name='čas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='salons.maker', verbose_name='kadeřnice / kosmetička')),
            ],
            options={
                'verbose_name': 'obsazený čas',
                'verbose_name_plural': 'obsazené časy',
                'ordering': ['time', 'maker_id'],
                'constraints': [models.UniqueConstraint(fields=('maker', 'time'), name='salons_maker_time_unique_maker_time')],
            },
        ),
    ]
