# Generated by Django 5.2.17 on 2026-10-05 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='název')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='rok')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='datum plesu')),
                ('stand_capacity', models.PositiveIntegerField(default=434, verbose_name='kapacita míst na stání')),
                ('stand_price', models.PositiveIntegerField(default=350, verbose_name='cena místa na stání (Kč)')),
                ('seat_price', models.PositiveIntegerField(default=500, verbose_name='cena sezení bez večeře (Kč)')),
                ('dinner_seat_price', models.PositiveIntegerField(default=750, verbose_name='cena sezení s večeří (Kč)')),
                ('complimentary_value', models.PositiveIntegerField(default=0, help_text='Odečte se od vybrané částky v přehledu.', verbose_name='hodnota volných lístků (Kč)')),
                ('is_active', models.BooleanField(default=False, verbose_name='aktivní')),
            ],
            options={
                'verbose_name': 'ročník',
                'verbose_name_plural': 'ročníky',
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='reservations_event_single_active', violation_error_message='Aktivní může být jen jeden ročník. Nejdřív zrušte aktivitu u jiného ročníku.')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='jméno')),
                ('email', models.CharField(max_length=125, verbose_name='e-mail')),
                ('tel', models.CharField(blank=True, max_length=155, verbose_name='telefon')),
                ('note', models.TextField(blank=True, verbose_name='poznámka')),
                ('stand', models.PositiveIntegerField(default=0, verbose_name='místa na stání')),
                ('price_all', models.PositiveIntegerField(default=0, verbose_name='cena celkem (Kč)')),
                ('status', models.IntegerField(default=1, verbose_name='stav')),
                ('date_payment', models.DateTimeField(blank=True, null=True, verbose_name='datum platby')),
                ('consent', models.BooleanField(default=True, verbose_name='souhlas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.event', verbose_name='ročník')),
            ],
            options={
                'verbose_name': 'rezervace',
                'verbose_name_plural': 'rezervace',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.PositiveSmallIntegerField(verbose_name='stůl')),
                ('letter', models.CharField(max_length=1, verbose_name='písmeno')),
                ('alias', models.CharField(max_length=10, verbose_name='označení')),
                ('kind', models.CharField(choices=[('raut', 'S večeří'), ('normal', 'Bez večeře')], default='normal', max_length=10, verbose_name='typ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='reservations.event', verbose_name='ročník')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='reservations.reservation', verbose_name='rezervace')),
            ],
            options={
                'verbose_name': 'místo',
                'verbose_name_plural': 'místa',
                'ordering': ['event_id', 'table', 'letter'],
                'constraints': [models.UniqueConstraint(fields=('event', 'alias'), name='reservations_seat_unique_alias_per_event')],
            },
        ),
    ]
