# Generated by Django 5.2.17 on 2026-10-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='role')),
                ('name', models.CharField(max_length=255, verbose_name='jméno')),
                ('email', models.CharField(max_length=255, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
            ],
            options={
                'verbose_name': 'kontakt',
                'verbose_name_plural': 'kontakty',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='název sekce')),
                ('content', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
            ],
            options={
                'verbose_name': 'text úvodní stránky',
                'verbose_name_plural': 'texty úvodní stránky',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TicketContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_from', models.DateField(verbose_name='prodej lístků od')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.contact', verbose_name='kontakt')),
            ],
            options={
                'verbose_name': 'prodej lístků',
                'verbose_name_plural': 'prodej lístků',
                'ordering': ['id'],
            },
        ),
    ]
